name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thankyou for contributing an issue to chessbot. A member of our team will review it and resolve it shortly.'
        pr-message: 'Thankyou for contributing to chessbot. A member of the team will review your PR shortly.'
